projects:
  jobsmanagement:
    schemaPath: web/src/graphql/schema.json
    includes:
      - web/src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: web/src/app/API.service.ts
        docsFilePath: web/src/graphql
extensions:
  amplify:
    version: 3
